language: node_js
git:
  depth: 3
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- pwd
- ls -all
addons:
  ssh_known_hosts: 120.78.221.76

before_install:
- openssl aes-256-cbc -K $encrypted_988f4d82d062_key -iv $encrypted_988f4d82d062_iv
  -in .pyramid_deploy_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa
after_success:
# - chmod 600 ~/.ssh/id_rsa
- ssh travis@120.78.221.76 -o StrictHostKeyChecking=no 'cd ~/pyramid && git pull -X theirs && cd server && yarn install && yarn run prod && cd ../app && yarn install && yarn run generate-prod && cp -r dist/. ~/nginx/html'
# before_deploy:
# - openssl aes-256-cbc -K $encrypted_988f4d82d062_key -iv $encrypted_988f4d82d062_iv -in .pyramid_deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"`
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa
# deploy:
#   provider: script
#   skip_cleanup: true
#   script:
#   - ssh prod@120.78.221.76 -o StrictHostKeyChecking=no 'cd ~/pyramid && git pull && cd server && yarn install && yarn run prod'
#   on:
#     branch: master

